services:

  nodejs:
    container_name: helloworld-nest.angel
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - PACKAGE_SCRIPT=test:e2e

    volumes:
      - ./src:/app/src
      - ./test:/app/test

    ports:
      - "3000:3000"
    restart: "no"