services:

  nodejs:
    image: nodejs/helloworld
    container_name: nodejs.helloworld-ts
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - NODE_SCRIPT=start:dev
    volumes:
      - ./src:/app/src

    ports:
      - "3000:3000"
    restart: "no"